import Head from 'next/head'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>NdFood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar data={data} />
        <Footer />
      </main>
    </>
  )
}

export async function getServerSideProps() {

  const {menu} = await import ('/data/data.json')
  return {
    props: {
      data: menu,
    }, 
  }
}